openapi: "3.0.0"
info:
  version: 1.0.0
  description: "Cette API permet de gérer des colocations en fonction des tâches à réaliser par chacun des membres."
  title: "Colocation API"
  contact:
    email: "lea.banquart@uha.fr"
    
servers:
  - url: "http://localhost:8080/"
tags:
- name: "Colocations"
  description: "Contrôle des colocations"
- name: "Users"
  description: "Contrôle des utilisateurs"
- name: "Tasks"
  description: "Contrôle des tâches"

paths:
  /colocations/add:
    post:
      tags:
      - "Colocations"
      summary: "Ajouter une nouvelle colocation"
      description: ""
      operationId: "addColocation"
      responses:
        '200':
          description: "Retourne l'ID de la colocation" 
  /colocations/addUser:
    post:
      tags:
      - "Colocations"
      summary: "Ajouter un nouveau habitant dans la colocation"
      description: ""
      operationId: "addOneUserInColocation"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la colocation"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "userID"
          in: "query"
          description: "ID de l'habitant à ajouter"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne la colocation"          
        '404':
          description: "L'utilisateur ou la colocation est introuvable, ou il existe déjà cet utilisateur dans la colocation."
  /colocations/removeUser:
    delete:
      tags:
      - "Colocations"
      summary: "Supprimer un nouveau habitant dans la colocation"
      description: ""
      operationId: "removeOneUserInColocation"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la colocation"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "userID"
          in: "query"
          description: "ID de l'habitant à supprimer"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne la colocation"
        '404':
          description: "L'utilisateur ou la colocation est introuvable, ou il existe déjà cet utilisateur dans la colocation."
  /colocations/addTask:
    post:
      tags:
      - "Colocations"
      summary: "Ajouter une nouvelle tâche à la colocation"
      description: ""
      operationId: "addOneTaskInColocation"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la colocation"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "description"
          in: "query"
          description: "Description de la tâche"
          required: true
          allowReserved: true
          schema:
            type: "string"
        - name: "points"
          in: "query"
          description: "Nombre de points de la tâche"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "askerId"
          in: "query"
          description: "ID du demandeur de la tâche"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne la colocation"          
        '404':
          description: "L'utilisateur ou la colocation est introuvable, ou il existe déjà cet utilisateur dans la colocation."
  /colocations/taskDone:
    post:
      tags:
      - "Colocations"
      summary: "Met une tâche 'faite'"
      description: ""
      operationId: "setOneTaskDoneInColocation"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la colocation"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "taskID"
          in: "query"
          description: "ID de la tâche à modifier"
          required: true
          allowReserved: true
          schema:
            type: "integer"
        - name: "donerID"
          in: "query"
          description: "ID de la personne ayant fait la tâche"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne 'successful operation'"
        '404':
          description: "L'utilisateur ou la colocation est introuvable, ou il existe déjà cet utilisateur dans la colocation."
  /colocations/delete:
    delete:
      tags:
      - "Colocations"
      summary: "Supprimer une colocation"
      description: ""
      operationId: "deleteColocation"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la colocation à supprimer"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description : "Retourne la colocation supprimée"
        '404':
          description: "La colocation est introuvable."
  /colocations/all:
    get:
      tags:
      - "Colocations"
      summary: "Récupérer toutes les colocations"
      description: ""
      operationId: "getAllColocations"
      responses:
        '200':
          description: "Liste de toutes les colocations"
          
  /users/add:
    post:
      tags:
      - "Users"
      summary: "Ajouter un utilisateur"
      description: ""
      operationId: "addUser"
      parameters:
        - name: "Name"
          in: "query"
          description: "Nom de l'utilisateur"
          required: true
          allowReserved: true
          schema:
            type : "string"
        - name: "Points"
          in: "query"
          description: "Points de l'utilisateur"
          required: true
          allowReserved: true
          schema:
            type : "integer"
      responses:
        '200':
          description: "Retourne l'ID de l'utilisateur'"
  /users/delete:
    delete:
      tags:
      - "Users"
      summary: "Supprimer un utilisateur"
      description: ""
      operationId: "deleteUser"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de l'utilisateur à supprimer"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne 'Deleted'"
        '404':
          description: "L'utilisateur est introuvable."
  /users/all:
    get:
      tags:
      - "Users"
      summary: "Récupérer tous les utilisateurs"
      description: ""
      operationId: "getAllUsers"
      responses:
        '200':
          description: "Retourne la liste de tous les utilisateurs"
  
  /tasks/delete:
    delete:
      tags:
      - "Tasks"
      summary: "Supprimer une tâche"
      description: ""
      operationId: "deleteTask"
      parameters:
        - name: "ID"
          in: "query"
          description: "ID de la tâche à supprimer"
          required: true
          allowReserved: true
          schema:
            type: "integer"
      responses:
        '200':
          description: "Retourne 'Deleted'"
        '404':
          description: "La tâche est introuvable."
  /tasks/all:
    get:
      tags:
      - "Tasks"
      summary: "Récupérer toutes les tâches"
      description: ""
      operationId: "getAllTasks"
      responses:
        '200':
          description: "La liste de toutes les tâches"
    
  

  
  
